EASY       = 0
MEDIUM     = 1
HARD       = 2
IMPOSSIBLE = 3

MIXED_DIFFICULTY = 4

DIFFICULTY_LABEL = {EASY: "easy", MEDIUM: "medium", HARD: "hard", IMPOSSIBLE: "impossible", MIXED_DIFFICULTY: "mixed"}

VALID_DIFFICULTIES      = {EASY, MEDIUM, HARD, IMPOSSIBLE}
VALID_PACK_DIFFICULTIES = {EASY, MEDIUM, HARD, IMPOSSIBLE, MIXED_DIFFICULTY}
