PERSON = 0
OBJECT = 1

EASY       = 0
MEDIUM     = 1
HARD       = 2
IMPOSSIBLE = 3

# For ChallengePack — can be mixed
MIXED_TYPE       = 2
MIXED_DIFFICULTY = 4

CHALLENGE_TYPE_LABEL = {PERSON: "person", OBJECT: "object", MIXED_TYPE: "mixed"}
DIFFICULTY_LABEL     = {EASY: "easy", MEDIUM: "medium", HARD: "hard", IMPOSSIBLE: "impossible", MIXED_DIFFICULTY: "mixed"}

VALID_CHALLENGE_TYPES  = {PERSON, OBJECT}
VALID_PACK_TYPES       = {PERSON, OBJECT, MIXED_TYPE}
VALID_DIFFICULTIES     = {EASY, MEDIUM, HARD, IMPOSSIBLE}
VALID_PACK_DIFFICULTIES = {EASY, MEDIUM, HARD, IMPOSSIBLE, MIXED_DIFFICULTY}
