"""unique username

Revision ID: 176df8c26760
Revises: e7697bebd7c5
Create Date: 2026-05-10 17:25:57.252760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176df8c26760'
down_revision = 'e7697bebd7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))

    # ### end Alembic commands ###
