"""add completed_at to games

Revision ID: 37047e5cc6c7
Revises: fb477bc7e889
Create Date: 2026-05-11 09:20:08.862837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37047e5cc6c7'
down_revision = 'fb477bc7e889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
