"""challenges subscription

Revision ID: 72f81c826574
Revises: 176df8c26760
Create Date: 2026-05-10 17:48:57.823008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72f81c826574'
down_revision = '176df8c26760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_packs',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('challenge_type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('difficulty', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('pack_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('challenge_type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('difficulty', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['challenge_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_pack_id'), ['pack_id'], unique=False)

    op.create_table('user_pack_accesses',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('pack_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['challenge_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pack_id', name='uq_user_pack')
    )
    with op.batch_alter_table('user_pack_accesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pack_accesses_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pack_accesses_user_id'), ['user_id'], unique=False)

    op.create_table('daily_challenges',
    sa.Column('challenge_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('available_on', sa.Date(), nullable=False),
    sa.Column('challenge_type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('difficulty', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('available_on', 'challenge_type', 'difficulty', name='uq_daily_slot')
    )
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_challenges_available_on'), ['available_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_challenges_challenge_id'), ['challenge_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_expires_at')

    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_challenges_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_daily_challenges_available_on'))

    op.drop_table('daily_challenges')
    with op.batch_alter_table('user_pack_accesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pack_accesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_pack_accesses_pack_id'))

    op.drop_table('user_pack_accesses')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_pack_id'))
        batch_op.drop_index(batch_op.f('ix_challenges_difficulty'))

    op.drop_table('challenges')
    op.drop_table('challenge_packs')
    # ### end Alembic commands ###
