"""add icon to challenges

Revision ID: 92772838eb65
Revises: a78e6ee22983
Create Date: 2026-05-11 21:14:53.085732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92772838eb65'
down_revision = 'a78e6ee22983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
