"""add daily slot unique constraint

Revision ID: 95264a11ee35
Revises: b6e4c2d8f901
Create Date: 2026-05-14 11:45:39.463841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95264a11ee35'
down_revision = 'b6e4c2d8f901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_daily_slot', ['available_on', 'difficulty'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.drop_constraint('uq_daily_slot', type_='unique')

    # ### end Alembic commands ###
