"""add subscription_access to challenge_packs

Revision ID: a78e6ee22983
Revises: 877753cb7c67
Create Date: 2026-05-11 21:12:10.855980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78e6ee22983'
down_revision = '877753cb7c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_packs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_access', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_packs', schema=None) as batch_op:
        batch_op.drop_column('subscription_access')

    # ### end Alembic commands ###
