"""empty message

Revision ID: e7697bebd7c5
Revises: 
Create Date: 2026-05-10 17:13:14.868182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7697bebd7c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('battles',
    sa.Column('challenge_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('player1_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('player2_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('current_turn_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('winner_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('status', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_turn_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battles_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battles_player1_id'), ['player1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battles_player2_id'), ['player2_id'], unique=False)

    op.create_table('friendships',
    sa.Column('requester_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('addressee_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('games',
    sa.Column('challenge_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_user_id'), ['user_id'], unique=False)

    op.create_table('battle_guesses',
    sa.Column('battle_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('response_code', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battle_guesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battle_guesses_battle_id'), ['battle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battle_guesses_user_id'), ['user_id'], unique=False)

    op.create_table('guesses',
    sa.Column('game_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('response_code', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('UUID_V7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guesses_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guesses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_guesses_game_id'))

    op.drop_table('guesses')
    with op.batch_alter_table('battle_guesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battle_guesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_battle_guesses_battle_id'))

    op.drop_table('battle_guesses')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_games_challenge_id'))

    op.drop_table('games')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battles_player2_id'))
        batch_op.drop_index(batch_op.f('ix_battles_player1_id'))
        batch_op.drop_index(batch_op.f('ix_battles_challenge_id'))

    op.drop_table('battles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
