"""energy fields

Revision ID: fb477bc7e889
Revises: 72f81c826574
Create Date: 2026-05-10 20:42:07.311583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb477bc7e889'
down_revision = '72f81c826574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_balance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('energy_replenished_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('energy_replenished_date')
        batch_op.drop_column('energy_balance')

    # ### end Alembic commands ###
