"""add is_battle to challenge_packs

Revision ID: ffb102f77a23
Revises: d8e1f4a72c93
Create Date: 2026-05-15 14:31:23.325475

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ffb102f77a23'
down_revision = 'd8e1f4a72c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_packs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_battle', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_packs', schema=None) as batch_op:
        batch_op.drop_column('is_battle')

    # ### end Alembic commands ###
